# Generated by Django 6.0.3 on 2026-03-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projects_projectimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectimages',
            name='image',
        ),
        migrations.AddField(
            model_name='postimages',
            name='link',
            field=models.URLField(default=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectimages',
            name='link',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
    ]
